# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy source code
COPY UnityMcpServer/src/ .

# Install dependencies and the package
RUN pip install --no-cache-dir .

# Default command to run the MCP server
CMD ["python", "server.py"]
